"""
Generate stub localisation entries for 48 Verne missions missing titles and descriptions.
These are placeholder entries that prevent the game from crashing on missing loc keys.

Format:
  a33_<mission_id>: 0 ## <Human-Readable Title>
  a33_<mission_id>_desc: "<Human-Readable Description>"

The _desc entries use generic Verne flavour text as placeholders.
Human-authored titles should replace these via ChatGPT or direct authoring.
"""

import re
from pathlib import Path

MISSIONS = [
    "A33_a_crimson_sea",
    "A33_a_matter_of_pride",
    "A33_a_most_prized_item",
    "A33_a_union_of_crowns",
    "A33_across_the_pond",
    "A33_all_roads_lead_to_verne",
    "A33_alvars_reforms",
    "A33_binding_the_beast",
    "A33_born_of_valour",
    "A33_break_the_queen_of_the_hill",
    "A33_corins_devout_protectors",
    "A33_corins_shield",
    "A33_expand_the_Vernissage",
    "A33_expand_the_wyvern_nests",
    "A33_in_search_of_adventure",
    "A33_in_the_name_corin",
    "A33_laments_regatta",
    "A33_new_verne",
    "A33_old_friends_old_rivals",
    "A33_on_wings_of_artificery",
    "A33_project_holohana",
    "A33_religious_mercantilism",
    "A33_spread_the_word",
    "A33_taking_to_the_seas",
    "A33_taming_the_lion",
    "A33_the_allure_of_the_luna",
    "A33_the_grand_port_of_heartspier",
    "A33_the_grand_vernissage",
    "A33_the_halanni_exposition",
    "A33_the_heart_of_darkness",
    "A33_the_holy_corinite_empire",
    "A33_the_kingdom_of_verne",
    "A33_the_lands_of_adventure",
    "A33_the_might_of_the_wyvern",
    "A33_the_quest_for_eggs",
    "A33_the_riches_of_the_khenak",
    "A33_the_rogue_duchy",
    "A33_the_sea_nest",
    "A33_the_verne_halann",
    "A33_the_vernissage",
    "A33_the_vernman_era",
    "A33_the_vernman_renaissance",
    "A33_the_wyvern_nest_initiative",
    "A33_type_2_wyverns",
    "A33_united_under_crimson_wings",
    "A33_valour_on_the_seas",
    "A33_with_sword_and_shield",
    "A33_zenith_of_the_eastern_princes",
]

# Generate placeholder title from mission ID
# A33_the_vernman_renaissance -> "The Vernman Renaissance"
# A33_expand_the_Vernissage -> "Expand the Vernissage"
# A33_project_holohana -> "Project Holohana"
def human_title(mid: str) -> str:
    name = mid.replace("A33_", "").replace("_", " ")
    # Title case, but keep Roman numerals and special words
    parts = name.split()
    result = []
    for i, part in enumerate(parts):
        if part.isupper() and len(part) > 1:
            result.append(part)  # e.g. "Vernissage" stays as-is if all caps
        else:
            result.append(part.capitalize())
    return " ".join(result)

LOC_PATH = Path(r"C:\Users\User\Documents\GitHub\My-Anbennar\localisation\verne_overhaul_l_english.yml")

# Read existing file
text = open(LOC_PATH, "rb").read().decode("utf-8-sig").replace("\r", "")
lines = text.split("\n")

# Find last non-empty line
last_idx = len(lines) - 1
while last_idx >= 0 and not lines[last_idx].strip():
    last_idx -= 1

# Append new entries
new_lines = []
new_lines.append("")
new_lines.append("# === STUB ENTRIES: missions with Paradox definitions but no localisation ===")
new_lines.append("# Auto-generated by generate_loc_stubs.py - replace 0 ## with real titles")
new_lines.append("")

for mid in sorted(MISSIONS):
    base = mid.lower()  # e.g. "a33_the_vernman_renaissance"
    title = human_title(mid)
    # Use value 0 as placeholder (same pattern as existing stub entries)
    new_lines.append(f'{base}: 0 "{title}"')
    new_lines.append(f'{base}_desc: 0 "Verne mission: {title}."')

new_lines.append("")
new_lines.append("# === END STUB ENTRIES ===")

# Insert before EOF marker or at end
insert_at = last_idx + 1
all_lines = lines[:insert_at] + new_lines + lines[insert_at:]

# Write back
out_text = "\n".join(all_lines)
# Normalise line endings
out_text = out_text.replace("\r", "").replace("\n", "\r\n")
open(LOC_PATH, "wb").write(out_text.encode("utf-8-sig"))

print(f"Appended {len(MISSIONS)} stub title + desc entries to:")
print(f"  {LOC_PATH}")
print()
print("NEXT STEP: Replace '0 ## <Title>' values with proper localised titles.")
print("  ChatGPT Modding project: paste the mission IDs and ask for title suggestions.")
